# We run on the container-based infrastructure, sudo is not allowed.
sudo: false
language: c

git:
    # If you use a depth of 1 and have a queue of jobs, Travis CI won’t build
    # commits that are in the queue when you push a new commit.
    depth: 3

# whitelist
branches:
    only:
        - master

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - valgrind
            - gfortran
            - realpath

# Travis CI C builder will export the CC env variable to point to gcc-4.8.
compiler:
    - gcc-4.8

script:
    - make -j 2 test
